#!/bin/bash
n=$(( $(echo $WATER | tr 'water' 01234) + $(echo $STIR | tr 'stir.' 0123456) )); r=""; a=bestchol; while [ $n -gt 0 ]; do r=${a:n%8:1}$r; n=$((n/8)); done; [ -z "$r" ] && echo b || echo $r
